(function(){
    const RULES={
        "Blackjack 21": {
            "title": "Reglas de Blackjack 21",
            "html": "\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-emerald-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🎯 Objetivo</h3>\n<p class=\"text-xs\">Sumar un total lo más cercano posible a <strong>21 puntos</strong> sin sobrepasarlo y superar la puntuación del crupier.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-amber-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🃏 Valor de Cartas</h3>\n<p class=\"text-xs\">• <strong>Cartas 2 al 10:</strong> Su valor numérico.<br/>• <strong>Figuras (J, Q, K):</strong> Valen 10 puntos.<br/>• <strong>As (A):</strong> Vale 11 o 1 según más convenga.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-cyan-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🎮 Acciones</h3>\n<p class=\"text-xs\">• <strong>Pedir:</strong> Recibe una carta adicional.<br/>• <strong>Plantarse:</strong> Te quedas con tu puntuación.<br/>• <strong>Doblar:</strong> Duplica la apuesta y recibe una única carta.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-purple-400 font-semibold mb-1 text-xs uppercase tracking-wider\">💰 Pagos</h3>\n<p class=\"text-xs\">• Victoria regular: <strong>1 a 1</strong>.<br/>• <strong>Blackjack natural (21 en 2 cartas):</strong> Paga <strong>3 a 2</strong>.<br/>• Empate: se devuelve la apuesta.</p>\n</div>\n"
        },
        "Higher & Lower": {
            "title": "Reglas de Higher & Lower",
            "html": "\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-emerald-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🎯 Objetivo</h3>\n<p>Predecir si el valor de la siguiente carta que saldrá de la baraja será <strong>Mayor</strong> o <strong>Menor</strong> que la carta visible.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-amber-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🃏 Jerarquía de Cartas</h3>\n<p>El <strong>As (A)</strong> es la carta más alta con valor de 14.</p>\n<p class=\"mt-1 text-xs text-slate-400\">Orden: 2, 3, 4, 5, 6, 7, 8, 9, 10, J(11), Q(12), K(13), A(14).</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-cyan-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🔥 Multiplicadores</h3>\n<p>Cada acierto consecutivo aumenta tu racha y multiplica tu premio acumulado (+50% por cada paso).</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-rose-400 font-semibold mb-1 text-xs uppercase tracking-wider\">⚠️ Riesgo &amp; Cobro</h3>\n<p>Puedes pulsar <strong>\"Cobrar Premio\"</strong> en cualquier momento para asegurar tus ganancias. Si fallas una predicción, perderás la apuesta de la ronda.</p>\n</div>\n"
        },
        "Ruleta": {
            "title": "Reglas de la Ruleta",
            "html": "\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-emerald-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🎯 Objetivo</h3>\n<p>Predecir en qué casilla numerada (0 al 36) caerá la bola tras el giro de la ruleta.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-amber-400 font-semibold mb-1 text-xs uppercase tracking-wider\">💰 Pagos de Apuestas</h3>\n<ul class=\"text-xs space-y-1.5 mt-1\">\n<li><strong class=\"text-white\">Pleno (1 número):</strong> Paga <span class=\"text-emerald-400 font-bold\">35 a 1</span>.</li>\n<li><strong class=\"text-white\">Docenas (12 números):</strong> Paga <span class=\"text-emerald-400 font-bold\">2 a 1</span>.</li>\n<li><strong class=\"text-white\">Columnas (12 números):</strong> Paga <span class=\"text-emerald-400 font-bold\">2 a 1</span>.</li>\n<li><strong class=\"text-white\">Rojo o Negro:</strong> Paga <span class=\"text-emerald-400 font-bold\">1 a 1</span>.</li>\n<li><strong class=\"text-white\">Par o Impar:</strong> Paga <span class=\"text-emerald-400 font-bold\">1 a 1</span>.</li>\n<li><strong class=\"text-white\">Bajo (1-18) / Alto (19-36):</strong> Paga <span class=\"text-emerald-400 font-bold\">1 a 1</span>.</li>\n</ul>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-cyan-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🟢 El Cero (0)</h3>\n<p class=\"text-xs\">El 0 es verde. Si la bola cae en el 0, únicamente ganan las apuestas colocadas directamente al número 0.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-purple-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🎲 Cómo Apostar</h3>\n<p class=\"text-xs\">1. Elige el valor de tu ficha ($10, $25, $50, $100, $500).<br/>2. Haz clic en las casillas deseadas del tapete.<br/>3. Presiona <strong>Girar Ruleta</strong> y mira rodar la bola.</p>\n</div>\n"
        },
        "Texas Hold'em": {
            "title": "📜 Reglas de esta versión",
            "html": "\n<div class=\"bg-slate-950/60 p-3 rounded-xl\">Hasta <strong>8 jugadores</strong> por mesa. Puedes escoger oponentes o dejar que se seleccionen al azar.</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl\">Hay <strong>12 bots</strong> con dificultades distintas. Su experiencia aumenta con las partidas jugadas y se muestra junto a su nombre.</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl\">La <strong>apuesta mínima se hereda</strong>: si en una ronda la apuesta máxima llegó a $40, la siguiente empieza con mínimo $40 o superior.</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl\">Al terminar la mano se muestran <strong>todas las cartas</strong>. Si un jugador se retira, sus cartas también se revelan en ese momento.</div>\n"
        },
        "Tragamonedas": {
            "title": "Reglas del Tragamonedas",
            "html": "\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-emerald-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🎯 Objetivo</h3>\n<p class=\"text-xs\">Alinear 3 símbolos idénticos en la línea central de pago para conseguir el premio mayor o 2 iguales para premio secundario.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-amber-400 font-semibold mb-1 text-xs uppercase tracking-wider\">💰 Tabla de Premios (3 Iguales)</h3>\n<ul class=\"text-xs space-y-1.5 mt-1\">\n<li class=\"flex justify-between\"><span>7️⃣ 7️⃣ 7️⃣ (Siete Dorado)</span> <strong class=\"text-amber-400\">50x</strong></li>\n<li class=\"flex justify-between\"><span>💎 💎 💎 (Diamante)</span> <strong class=\"text-cyan-400\">25x</strong></li>\n<li class=\"flex justify-between\"><span>👑 👑 👑 (Corona)</span> <strong class=\"text-purple-400\">15x</strong></li>\n<li class=\"flex justify-between\"><span>🔔 🔔 🔔 (Campana)</span> <strong class=\"text-yellow-400\">10x</strong></li>\n<li class=\"flex justify-between\"><span>🍇 🍇 🍇 (Uvas)</span> <strong class=\"text-emerald-400\">5x</strong></li>\n<li class=\"flex justify-between\"><span>🍒 🍒 🍒 (Cerezas)</span> <strong class=\"text-rose-400\">3x</strong></li>\n</ul>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-cyan-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🍒 Premio por Pareja</h3>\n<p class=\"text-xs\">Cualquier combinación con <strong>2 símbolos iguales</strong> paga <strong class=\"text-emerald-400\">1.5x</strong> tu apuesta.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-purple-400 font-semibold mb-1 text-xs uppercase tracking-wider\">💡 Cómo Jugar</h3>\n<p class=\"text-xs\">1. Ajusta tu apuesta con los botones rápidos.<br/>2. Presiona <strong>¡GIRAR RODILLOS!</strong> y celebra tus premios.</p>\n</div>\n"
        },
        "Video Poker": {
            "title": "Reglas de Video Poker",
            "html": "\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-emerald-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🎴 1. Reparto Inicial</h3>\n<p class=\"text-xs\">Se reparten <strong>5 cartas descubiertas</strong> desde una baraja francesa completa de 52 cartas.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-amber-400 font-semibold mb-1 text-xs uppercase tracking-wider\">📌 2. Selección de cartas a cambiar</h3>\n<p class=\"text-xs\">Haz clic en las cartas que deseas cambiar (se marcarán con <strong>CAMBIAR</strong>). También puedes usar las teclas <strong>1 al 5</strong> del teclado.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-cyan-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🔄 3. Descarte y Reemplazo</h3>\n<p class=\"text-xs\">Pulsa <strong>CAMBIAR (DRAW)</strong>: las cartas seleccionadas se descartarán y se reemplazarán por cartas nuevas; las no seleccionadas se conservarán.</p>\n</div>\n<div class=\"bg-slate-950/60 p-3 rounded-xl border border-slate-800/60\">\n<h3 class=\"text-purple-400 font-semibold mb-1 text-xs uppercase tracking-wider\">🏆 4. Evaluación &amp; Jacks or Better</h3>\n<p class=\"text-xs\">Para ganar, necesitas al menos una <strong>pareja de Jotas (J) o superior (Q, K, A)</strong>. Cuanto más alta tu combinación final, mayor será tu premio según la tabla.</p>\n</div>\n"
        }
    };
    function gameKey(){
        const p=location.pathname.toLowerCase();
        if(p.includes('blackjack')) return 'Blackjack 21';
        if(p.includes('higher_lower')) return 'Higher & Lower';
        if(p.includes('ruleta')) return 'Ruleta';
        if(p.includes('texas_holdem')) return "Texas Hold'em";
        if(p.includes('tragamonedas')) return 'Tragamonedas';
        if(p.includes('video_poker')) return 'Video Poker';
        return null;
    }
    function mount(){
        const h1=document.querySelector('h1'); if(!h1||document.getElementById('rules-button')) return;
        const data=RULES[gameKey()]; if(!data) return;
        const btn=document.createElement('button'); btn.id='rules-button'; btn.className='rules-button'; btn.type='button'; btn.textContent='📜 Reglas';
        h1.parentElement?.classList.add('casino-title-row');
        h1.insertAdjacentElement('afterend',btn);
        const modal=document.createElement('div'); modal.id='rules-modal'; modal.className='casino-modal hidden';
        modal.innerHTML=`<div class="casino-modal-card"><div class="rules-modal-head"><div><h2>📜 ${data.title}</h2></div><button class="modal-close" type="button" aria-label="Cerrar">×</button></div><div class="rules-modal-content">${data.html}</div></div>`;
        document.body.appendChild(modal);
        const close=()=>modal.classList.add('hidden');
        btn.addEventListener('click',()=>modal.classList.remove('hidden'));
        modal.querySelector('.modal-close').addEventListener('click',close);
        modal.addEventListener('click',e=>{if(e.target===modal)close()});
        document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
    }
    document.addEventListener('DOMContentLoaded',mount);
})();
