(function(){
    const LOANS_KEY='casino_loans', BALANCE_KEY='casino_balance', MAX_LOANS=3, MAX_AMOUNT=1000;
    const readLoans=()=>{try{return JSON.parse(localStorage.getItem(LOANS_KEY)||'[]')}catch(_){return[]}};
    const saveLoans=loans=>{localStorage.setItem(LOANS_KEY,JSON.stringify(loans));window.dispatchEvent(new CustomEvent('casino-loans-changed'))};
    const getBalance=()=>{const n=parseInt(localStorage.getItem(BALANCE_KEY),10);return Number.isFinite(n)?n:1000};
    const setBalance=v=>{const safe=Math.max(0,Math.floor(Number(v)||0));localStorage.setItem(BALANCE_KEY,String(safe));const el=document.getElementById('fichas-count');if(el)el.textContent=safe;window.dispatchEvent(new CustomEvent('casino-balance-changed',{detail:{balance:safe}}));refresh()};
    const money=n=>'$'+Math.max(0,Math.floor(n)).toLocaleString('es-PE');
    const canPlay=cost=>getBalance()>=Math.max(0,Math.floor(Number(cost)||0));
    window.CasinoFinanzasCanPlay=canPlay;
    function message(t,ok){const e=document.getElementById('loan-message');if(e){e.textContent=t;e.className='loan-message '+(ok?'success':'error')}}
    function requestLoan(){const input=document.getElementById('loan-amount');const amount=Math.floor(Number(input?.value));const loans=readLoans();if(loans.length>=MAX_LOANS){message('Ya tienes 3 préstamos. Debes pagarlos todos antes de solicitar otro.',false);return}if(!Number.isFinite(amount)||amount<1||amount>MAX_AMOUNT){message('El préstamo debe ser entre $1 y $1,000.',false);return}loans.push({id:Date.now()+Math.random(),amount,remaining:amount,createdAt:new Date().toISOString()});saveLoans(loans);setBalance(getBalance()+amount);message(`Préstamo aprobado: ${money(amount)}.`,true);refresh()}
    function payLoan(id){let loans=readLoans();const loan=loans.find(l=>String(l.id)===String(id));if(!loan)return;const input=document.getElementById(`loan-pay-${id}`);const requested=Math.floor(Number(input?.value));const payment=Math.min(requested,loan.remaining,getBalance());if(payment<=0){message('Monto inválido o saldo insuficiente.',false);return}loan.remaining-=payment;setBalance(getBalance()-payment);loans=loans.filter(l=>l.remaining>0);if(!loans.length){localStorage.removeItem(LOANS_KEY);window.dispatchEvent(new CustomEvent('casino-loans-changed'));message('¡Todos los préstamos fueron pagados! Puedes volver a solicitar hasta 3.',true)}else{saveLoans(loans);message(`Pago realizado: ${money(payment)}.`,true)}refresh()}
    function payAll(){const loans=readLoans();const total=loans.reduce((s,l)=>s+l.remaining,0);if(!loans.length)return;if(getBalance()<total){message(`Necesitas ${money(total)} para pagar todos los préstamos.`,false);return}setBalance(getBalance()-total);localStorage.removeItem(LOANS_KEY);window.dispatchEvent(new CustomEvent('casino-loans-changed'));message('¡Todos los préstamos fueron pagados!',true);refresh()}
    function refresh(){const loans=readLoans(),balance=getBalance(),debt=loans.reduce((s,l)=>s+l.remaining,0);const count=document.getElementById('loan-count'),debtEl=document.getElementById('loan-debt'),list=document.getElementById('loan-list'),req=document.getElementById('loan-request'),all=document.getElementById('loan-pay-all');if(count)count.textContent=`${loans.length}/${MAX_LOANS}`;if(debtEl)debtEl.textContent=money(debt);if(req)req.disabled=loans.length>=MAX_LOANS;if(list){list.innerHTML=loans.length?loans.map((l,i)=>`<div class="loan-card"><div><strong>Préstamo ${i+1}</strong><span>Restante: ${money(l.remaining)}</span></div><div class="loan-pay-row"><input id="loan-pay-${l.id}" type="number" min="1" max="${Math.min(l.remaining,balance)}" placeholder="Monto" ${balance<=0?'disabled':''}><button type="button" class="loan-pay-btn" data-loan-id="${l.id}" ${balance<=0?'disabled':''}>Pagar</button></div></div>`).join(''):'<p class="loan-empty">No tienes préstamos activos.</p>';list.querySelectorAll('[data-loan-id]').forEach(b=>b.addEventListener('click',()=>payLoan(b.dataset.loanId)))}if(all)all.disabled=!loans.length||balance<debt;const bal=document.getElementById('fichas-count');if(bal)bal.textContent=balance}
    function open(){document.getElementById('loan-modal')?.classList.remove('hidden');refresh()}
    function close(){document.getElementById('loan-modal')?.classList.add('hidden')}
    function mount(){
        if(document.getElementById('loan-open'))return;
        const balance=document.getElementById('fichas-count');
        if(!balance)return;
        const host=balance.closest('div');
        const btn=document.createElement('button'); btn.id='loan-open'; btn.className='loan-open-btn'; btn.type='button'; btn.title='Abrir préstamos'; btn.textContent='💳 Préstamo';
        host?.appendChild(btn);
        const modal=document.createElement('div');modal.id='loan-modal';modal.className='loan-modal hidden';modal.innerHTML=`<div class="loan-modal-card"><div class="loan-modal-head"><div><h2>💳 Préstamos</h2><p>Máximo 3 préstamos activos. Cada préstamo puede ser de hasta $1,000.</p></div><button id="loan-close" class="loan-close" type="button">×</button></div><div class="loan-stats"><div><span>Activos</span><strong id="loan-count">0/3</strong></div><div><span>Deuda</span><strong id="loan-debt">$0</strong></div></div><div class="loan-request-box"><label for="loan-amount">Monto del nuevo préstamo</label><div class="loan-input-row"><input id="loan-amount" type="number" min="1" max="1000" value="1000"><button id="loan-request" type="button">Solicitar</button></div></div><div id="loan-message" class="loan-message"></div><div id="loan-list" class="loan-list"></div><button id="loan-pay-all" type="button" class="loan-pay-all">Pagar todos</button></div>`;document.body.appendChild(modal);
        btn.addEventListener('click',open);document.getElementById('loan-close').addEventListener('click',close);document.getElementById('loan-request').addEventListener('click',requestLoan);document.getElementById('loan-pay-all').addEventListener('click',payAll);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.addEventListener('casino-loans-changed',refresh);window.addEventListener('casino-balance-changed',refresh);refresh();
    }
    window.CasinoFinanzas={getBalance,setBalance,getLoans:readLoans,refresh,MAX_LOANS,MAX_AMOUNT};document.addEventListener('DOMContentLoaded',mount)
})();
